### ISSUE TITLE
Error importing '*.ts' files

### ISSUE THREAD

**Issue by innomatica** [slack-samples/deno-starter-template#43] opened 2023-07-24 16:28 UTC
I created a project following [the quick start guide](https://api.slack.com/automation/quickstart#create-app).
```
slack create my-app --template https://github.com/slack-samples/deno-starter-template
```

In the vs code (deno plugin installed), all `import` lines are marked as errors. Either

>Cannot find module 'https://deno.land/std@0.153.0/testing/asserts.ts' or its corresponding type declarations.ts(2307)

or
>An import path can only end with a '.ts' extension when 'allowImportingTsExtensions' is enabled.ts(5097)

I know this is silly question. But I couldn't find solution elsewhere.

**Comment by hello-ashleyintech** [comment] 2023-07-24 16:34
Hi, @innomatica! Thanks for your question!

I am unable to reproduce this on my side, which leads me to believe it may be an error with your local VSCode and Deno extension.

After installing the Deno plugin, have you tried completely restarting your VSCode and then re-opening your application in VSCode to see if it still produces the same error?

I hope this helps! 🙌

**Comment by innomatica** [comment] 2023-07-24 16:38
Thanks for the quick reply.

I just figured out what has happened. I accidentally opened the vs code in the parent folder, not the project folder itself. In other words, I skipped the step
```
cd my-app
```

False alarm, sorry.

**Comment by hello-ashleyintech** [comment] 2023-07-24 17:36
No worries at all ❤️ I'll close this issue but please feel free to submit another one if you run into any trouble!

**Closed by hello-ashleyintech** 2023-07-24 17:36 UTC
Labels: question
